name: Check for Go dependency updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"
  pull_request:
    paths:
      - .github/workflows/update-k8sd-go-deps.yaml

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Update Go dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Create pull request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[main] Update Go dependencies"
          title: "[main] Update Go dependencies"
          body: "[main] Update Go dependencies"
          branch: "autoupdate/go-deps/main"
          labels: |
            automerge
          delete-branch: true
          token: ${{ secrets.BOT_TOKEN }}
          author: "K8s builder bot <k8s-bot@canonical.com>"
